### ISSUE TITLE
Add travis integration

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/microservices#2]
Connect project to travis and build each time when receiving PR
Need to create `.travis.yml` (you can see [sample here](https://github.com/JuniorsJava/itevents/blob/master/.travis.yml) ) to run `mvn clean install -Pqulice` in gamification on every Pull Request. But first need to install slack api from another microservice (would be nice to add this information to readme file).
Make fork from this repo, use google to know how is it working, and make sure it works. Please, provide link on PR in your repo and travis build log.
**UPD**: cd simple-slack-api. Run `gradle clean install` to install dependency to your local maven repository.

**Comment by vkuchyn** [comment]
@danilkuznetsov you can take it to work. Please - give me know when you started

**Comment by vkuchyn** [comment]
@danilkuznetsov see update about installing slack-api

**Comment by danilkuznetsov** [comment]
@vkuchyn hi, i started

**Comment by danilkuznetsov** [comment]
@vkuchyn i finished, pls view link on my test pull request and build logs
https://travis-ci.org/danilkuznetsov/microservices
https://github.com/danilkuznetsov/microservices/pull/1
