### ISSUE TITLE
Implement Points GUI

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/microservices#31]
Implement SPA (using [Angular 1](https://angularjs.org/) and [Bootstrap](https://getbootstrap.com/) ) 
UI should make ajax request to server and show next table:

email | Skype | slack | total | Details to | Details from 
------ | ------- | ------ | ----- |------------ | -----------------
mail@a.com  | skype.id | slack | 20 | Link to show detailed from whom points received | Link to show detailed information to whom user gave points

Columns from email - total are trivial, should show information from user profile. 
 
By clicking on link in column `Details to` subtable should popup that show result of addition request to server - information who gave point to current user with description.

User From | How much | Description
-------------- | -------------- | ----------------
[User](Link to user in table) | 1 | Thanks for help with lab 21

Instead of requesting real server - put mock json file with response structure to resource folder.
JSON structure TBD.

**Comment by danilkuznetsov** [comment]
@vkuchyn  hi, i started

**Comment by vkuchyn** [comment]
@danilkuznetsov how is going? Please - don't lock this task, provide smaller part of the task for review (layout, part of logic, etc)

**Comment by danilkuznetsov** [comment]
@vkuchyn 
hi, i finished, pls review

**Comment by vkuchyn** [comment]
@danilkuznetsov thanks, will do soon
