### ISSUE TITLE
Fix build on CI

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/microservices#34]
Fix [build on CI](https://travis-ci.org/JuniorsJava/microservices/builds/141586027)

**Comment by vkuchyn** [comment]
@dtantsev this task is yours. Please - give a voice when you started

**Comment by dtantsev** [comment]
@vkuchyn i've just started. Bug method found. I'll try to fix

**Comment by dtantsev** [comment]
@vkuchyn: fixed. Please, review
