### ISSUE TITLE
Use rultor for merge

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/microservices#35]
To avoid situation happened in #34 (all tests are fine but after merge - failed) we can use service http://rultor.com/
It has feature smart merge - before merge on github - merges locally, run again build with all tests and then if everything is ok - merges on github
The same logic for deploy
Also it's configuration  is very similar to travis

**Comment by vkuchyn** [comment]
@danilkuznetsov this task is yours. Give a voice after start, feel free to ask questions

**Comment by danilkuznetsov** [comment]
@vkuchyn  hi, i started

**Comment by danilkuznetsov** [comment]
@vkuchyn  i finished, pls review

**Comment by danilkuznetsov** [comment]
@vkuchyn update github permissions for rultor, because 
`
git push origin master
ERROR: Permission to JuniorsJava/microservices.git denied to rultor.
fatal: Could not read from remote repository.
`

**Comment by vkuchyn** [comment]
@danilkuznetsov done.

**Comment by vkuchyn** [comment]
@rultor merge, pls
