### ISSUE TITLE
Fix PMD violations

### ISSUE THREAD

**Issue by vkuchyn** [JuniorsJava/microservices#4]
We have 13 PMD violations raises by plugin qulice. Need to fix them.

**Comment by vkuchyn** [comment]
@sLisnychyi I hope, you know what to do ) Run `mvn clean install -Pqulcie` and follow "the rabbit" (error descriptions).

**Comment by sLisnychyi** [comment]
@vkuchyn 
hi, i checked PMD issues, but I was unable to find a solution to my problems.
Left the following issues:

1. Issues connected to package-info.java class
[ERROR] \src\main\java\juja\microservices\gamification\jersey\package-info.java[1]: Missing a header - not enough lines in file. (HeaderCheck)

2. Issue connected to license comment. Qualice doesn't like header.
I tried various combinations and still get the errors.
 Line does not match expected header line of ' *'. (HeaderCheck)

**Comment by vkuchyn** [comment]
@sLisnychyi thanks, I will take a look soon.

**Comment by vkuchyn** [comment]
@sLisnychyi pls, create PR for review

**Comment by sLisnychyi** [comment]
@vkuchyn there's nothing to review. i just want to know how to fix this if it possible

**Comment by vkuchyn** [comment]
@sLisnychyi 
> Issue connected to license comment. Qualice doesn't like header.
I tried various combinations and still get the errors.
Line does not match expected header line of ' *'. (HeaderCheck)

Seems, auto code-reformate of IDEA put tag <p/> to empty line. This caused this exception.

I suppose - the same problem with point 1. 
BTW - I don't see these exceptions now, so seems they occurred while refactoring. Take a look at changes you've made and you will found the cause

**Comment by sLisnychyi** [comment]
> BTW - I don't see these exceptions now, so seems they occurred while refactoring.
So, you have no PMD violations and success build?

**Comment by vkuchyn** [comment]
@sLisnychyi I am sorry for inaccuracy. I meant those violations you was talking about https://github.com/JuniorsJava/microservices/issues/4#issuecomment-215402333

**Comment by sLisnychyi** [comment]
@vkuchyn 
can you send these 13 PMD violations that you mentioned at the begging.

because for now i have only these ones:

> Issues connected to package-info.java class
[ERROR] \src\main\java\juja\microservices\gamification\jersey\package-info.java[1]: Missing a header - not enough lines in file. (HeaderCheck)

> Issue connected to license comment. Qualice doesn't like header.
I tried various combinations and still get the errors.
Line does not match expected header line of ' *'. (HeaderCheck)

> Lines in file should end with Unix-like end of line (RegexpMultilineCheck)

**Comment by vkuchyn** [comment]
@sLisnychyi checkout master, run build - you will see.

**Comment by vkuchyn** [comment]
@sLisnychyi fixed in #6
