### ISSUE TITLE
Admin can create user

### ISSUE THREAD

**Issue by OlgaKulikova** [JuniorsJava/microservices#45]
User has username, role, skype, slack
This action should be carried out through chain from Controller to DB, covered by tests.
Also check token in Controller (security).

**Comment by vkuchyn** [comment]
@OlgaKulikova Is there some code to merge in scope of this task? I cannot see any Pull Request connected to it.

**Comment by OlgaKulikova** [comment]
@vkuchyn This issue is closed because of uselessness. No code.
